### ISSUE TITLE
Example Profile picture doesn't load on /docs

### ISSUE THREAD

**Issue by evanzhong** [uclaacm/teach-la-website#136]
![image](https://user-images.githubusercontent.com/23728476/97791686-4a42d080-1b92-11eb-8070-c1cdd7b3dda1.png)

Looks like https://api.adorable.io/ is down / has been down for a while?

We're hard linking to 
![image](https://user-images.githubusercontent.com/23728476/97791659-1667ab00-1b92-11eb-819f-3ca1fefa11dd.png)

**Comment by malsf21** [comment]
Yup, thanks for catching this! I noticed this earlier on but forgot to change the docs example, great catch!
