### ISSUE TITLE
Improving pre/code blocks with width-control and monospaced fonts

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#148]
@surreally brought up a great point in the discussion in #145:

* right now, we don't have any width-control mechanism for our `<pre>-<code>` combination - it just overflows
* right now, our font stack for `code` is not particularly readable

With that in mind, we should look to rectify both of these issues! 

* for width-control: we can consider either setting a scrollbar (with `overflow-x: scroll` and a fixed width), or soft-wrapping the lines. To whoever implements this ticket, you should research both options and see what works better!
* for our monospace font: we can consider picking something already on the system (there is a common monospace system font stack), or use an externally-loaded font like Fira Mono. for whoever implements this ticket: we should look into how adding an external font impacts our user experience, and then decide accordingly from there.

**Comment by malsf21** [comment]
Quick update for @EinarBalan: Design just released their guideline, and the official word is that `Source Code Pro` is our monospace font. See guidelines: https://design.uclaacm.com/guidelines/

**Comment by EinarBalan** [comment]
> Quick update for @EinarBalan: Design just released their guideline, and the official word is that `Source Code Pro` is our monospace font. See guidelines: https://design.uclaacm.com/guidelines/

Dang it I literally just committed with Fira Mono lol. I'll go back and change it. Also, while I'm here I'll say that I implemented the horizontal scrolling, but it doesn't seem to be a great solution... you'll see what I mean.

I tried to add the soft wrapping as I feel that that would definitely be a better solution, but I can't get it to work :/
Maybe someone who's more experienced than me can add that?

**Comment by malsf21** [comment]
Oh no! Haha sorry for the awkwardness on the communication, thank you for working on it so far though!

If you open a PR, I can try to help you troubleshoot the horizontal scrolling or the soft wrapping! Curious to see what's going on with the horizontal scroll. Two links that may help you with soft wrap:

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap

https://stackoverflow.com/questions/248011/how-do-i-wrap-text-in-a-pre-tag

**Comment by EinarBalan** [comment]
Just opened the PR and managed to get soft wrapping working, thanks for the links!
