### ISSUE TITLE
Temporary Location for Python Videos

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#154]
Eventually, #58 will be the home of our Python curriculum, but for now we should bop the videos in an easily-accessible place! I think the Resources page is a good place to start, and we can link to the videos from the classes page.

**Comment by malsf21** [comment]
Blocked because we're figuring out video uploading!

**Comment by krashanoff** [comment]
> figuring out video uploading!

This is a great point. I would think keeping it in Google Drive along with our slide decks would be a good idea, but we could always consider just putting it on YouTube unlisted.

**Comment by malsf21** [comment]
At this point, #155 is probably going to get done in time, so going to close this!
