### ISSUE TITLE
Display secondary role on individual team member page

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#162]
Something that I've noticed but we've never really gotten around to is that the individual team member pages don't display the secondary role properly. For example, see Arjun's general entry:

![Screen Shot 2020-11-28 at 9 29 23 PM](https://user-images.githubusercontent.com/14893287/100534177-d6abd780-31c0-11eb-9941-64b733ab52d8.png)

Compared to his team page entry:

![Screen Shot 2020-11-28 at 9 30 25 PM](https://user-images.githubusercontent.com/14893287/100534198-0c50c080-31c1-11eb-91e6-d7098d790dbf.png)

Should be a simple fix!

**Comment by Harshith2255** [comment]
hello
i would like to contribute to this project

**Comment by malsf21** [comment]
Hey @Harshith2255 - I'll leave a similar message to the other ticket. If you'd like to take this ticket, feel free to give it a shot! You can read our contribution workflow (and how to get started) in our project repository's [README file](https://github.com/uclaacm/teach-la-website/blob/master/README.md) - check it out and let me know what you think!

**Comment by Harshith2255** [comment]
I am sorry i am right now caught up in something
