### ISSUE TITLE
Implement a more obvious way to get to a team member's page

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#163]
Right now, you have to click on the member's image to get to their individual team page. This is not very intuitive, and it's not very accessible either - we should brainstorm a better way to do this.

A few options:
* a button
* a hard link
* an icon

We should experiment and see what seems natural!

**Comment by Harshith2255** [comment]
hello @malsf21 
I would like to contribute to this project.

**Comment by malsf21** [comment]
Hey @Harshith2255, if you'd like to take this ticket, feel free to give it a shot! You can read our contribution workflow (and how to get started) in our project repository's [README file](https://github.com/uclaacm/teach-la-website/blob/master/README.md) - check it out and let me know what you think!

**Comment by krashanoff** [comment]
Closed by #212
