### ISSUE TITLE
Blog: Related Articles Image Overflow on Mobile

### ISSUE THREAD

**Issue by EinarBalan** [uclaacm/teach-la-website#209]
## Related Articles Mobile Image Overflow

Opened the blog page while in a LinkedIn mobile browser (don't ask lol) and saw this:

![Image](https://user-images.githubusercontent.com/40647794/104675209-dfd20480-5699-11eb-8952-9a5a9851821d.PNG)

I did some poking around and noticed its not just a weird LinkedIn issue but actually happens on all small width screens.  My guess is that it could be resolved with a max width css prop, but I've done *no* testing so that might be completely wrong. Could be a good first issue!

**Comment by malsf21** [comment]
Haha, great catch @EinarBalan (and I won't ask). I agree this is a bug that needs fixing, and a good first issue!

Probably what's going on: something has a static min-width when it shouldn't. Or, something has a fixed width and it shouldn't? 

As an aside, we should probably reduce the gutters on mobile, we're losing too much screen real estate. Probably another issue (though it may be related to this problem as well).
