### ISSUE TITLE
Create a "Resources for Devs" Page

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/teach-la-website#234]
As we've amalgamated and produced more dev resources, we should link to them somewhere! I propose we create a new dev page that lists resources that we (Teach LA + Teach LA adjacent) have made; in particular, this includes:

* learning lab crash course
* QWER Hacks React / Firebase workshops ('21 and '20)
* react starter barebones 
* Dev Intern W'21 Training

As we produce more resources, we should add them to this list too!

**Comment by malsf21** [comment]
GitHub Links: 

* [React Starter](https://github.com/uclaacm/teach-la-react-starter-barebones)
* [Learning Labs Crash Course](https://github.com/uclaacm/learning-lab-crash-course-su20)
* [Dev Intern W'21](https://github.com/uclaacm/tla-dev-intern-training-w21)
* [QWER Hacks '21](https://github.com/malsf21/qwerhacks-21-workshops) <- there are two youtube playlists in here
* [QWER Hacks '20](https://github.com/malsf21/qwerhacks-web-dev-workshop)

YT Playlist:

* [Learning Lab Crash Course](https://www.youtube.com/playlist?list=PLPO7_kXilXFa6YdXxn5oln1gagcqnFI4l)
