### ISSUE TITLE
Remove GitHub Actions around Deployment

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/teach-la-website#297]
I switched our main domain to deploy off of Netlify instead of GitHub Pages. This means we can remove our deployment action and deactivate (my) secret key, and remove the `CNAME` file!

(might need a bit of testing to make sure I didn't make any mistakes)

**Comment by vivianha534** [comment]
![deploymentAction](https://user-images.githubusercontent.com/56574435/112803581-4ecbc200-9028-11eb-8b60-db6ab78c874f.JPG)

Would this be the correct way to remove our deployment action?

**Comment by mattxwang** [comment]
Ooh no, we still want to keep our test actions. I would:

* delete `deploy.yml` in `.github/workflows`
* disable GitHub Pages from the options tab
* delete the `CNAME` file
* update our badge in our README
