### ISSUE TITLE
Remove google link redirects in '21-'22 Dev Reflections

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/teach-la-website#428]
Super excited to read #425!!

I noticed that some of the links have Google's redirect built-in, ex

```markdown
- [Our Website!](https://www.google.com/url?q=https://teachla.uclaacm.com/&sa=D&source=editors&ust=1663828915566951&usg=AOvVaw0jRSQI_D1nkGGLcoQviawJ)
```
We should remove these + the post-tracking links!

cc: @reginawang3495

**Comment by reginawang3495** [comment]
Fixed by https://github.com/uclaacm/teach-la-website/commit/a514d911434326c039227e2bc153070652c36dae I believe!
