### ISSUE TITLE
Update CSS of Upper Nav Bar

### ISSUE THREAD

**Issue by Nhamakami7** [uclaacm/teach-la-website#433]
The upper nav bar needs to be updated from the old design to the new design!

Old Nav Bar:
![image](https://user-images.githubusercontent.com/25124783/197693370-a558062b-9590-436e-99e7-1f433f7d7b54.png)

New Nav Bar:
![image](https://user-images.githubusercontent.com/25124783/197693532-28d9dc9f-c5fc-4827-a14e-9b901b6e5281.png)

In other words, we need to change the styling of:
1) The 'acm.teachLA' text
2) The 'join us' button
3) The lower border of nav bar

Find the Figma for the new design here:
https://www.figma.com/file/hCeUDv4rdByyidB3lVTDQZ/TLA-Website-2022?node-id=0%3A1

**Comment by Halim-Shams** [comment]
Hey  I'd like to work on this project
