### ISSUE TITLE
Partnered Schools Page

### ISSUE THREAD

**Issue by malsf21** [uclaacm/teach-la-website#64]
We should flesh out our `/schools` page to have more information about our partner schools, and how others can join us.

Current partner schools:

* Emerson Elementary School
* North Hollywood High School
* Sepulveda Middle School
* Brockton Elementary School

Prev. Partner schools
* Mark Twain Middle School
* Archer School for Girls
* Marlborough School

**Comment by krashanoff** [comment]
Assigning @joshSi
